export enum TypeMedia {
  PRODUCT_THUMBNAIL_CATEGORY = 1,
  PRODUCT_IMAGE_DETAIL = 2,
  PRODUCT_THUMBNAIL_BACKGROUND = 3,
  USER_AVATAR = 4,
  BRAND_THUMBNAIL = 5,
  CATEGORY_THUMBNAIL = 6,
  CLASSIFY_THUMBNAIL = 7,
  PRODUCT_VIDEO = 8,
}
